# Generated by Django 4.2.3 on 2023-07-30 10:09

from django.db import migrations
import mainpage.fields
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=mainpage.fields.WEBPField(blank=True, default='media/Models/no_image_big.png', null=True, upload_to=mainpage.models.image_folder_Course, verbose_name='Изображение курса'),
        ),
    ]
