# Generated by Django 4.2.3 on 2023-08-02 16:12

import django.core.validators
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('C++', 'C++'), ('Java', 'Java'), ('C#', 'C#'), ('Pascal', 'Pascal'), ('JavaScript', 'JavaScript'), ('Ruby', 'Ruby'), ('Swift', 'Swift'), ('PHP', 'PHP'), ('TypeScript', 'TypeScript'), ('Go', 'Go'), ('Kotlin', 'Kotlin')], default='Python', max_length=72, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Применяемы языки'),
        ),
    ]
