# Generated by Django 4.2.3 on 2023-07-12 17:14

import datetime
from django.db import migrations, models
import mainpage.fields
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=mainpage.fields.WEBPField(default='media/Models/no_image_big.png', upload_to=mainpage.models.image_folder_Course, verbose_name='Изображение курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tech_img',
            field=mainpage.fields.WEBPField(default='media/Models/no_image_big.png', upload_to=mainpage.models.image_folder_Technology, verbose_name='Изображение языка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='Время начала курса'),
        ),
    ]
