# Generated by Django 4.2.2 on 2023-06-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_des',
            field=models.TextField(default='', max_length=320, verbose_name='Краткое описание'),
        ),
    ]
