# Generated by Django 4.2.2 on 2023-06-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_course_days_of_week_course_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='available_courses',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wallet',
        ),
        migrations.AddField(
            model_name='customuser',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
