# Generated by Django 4.2.2 on 2023-06-30 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_past',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='Время начала курса'),
        ),
    ]
