# Generated by Django 4.2.2 on 2023-06-20 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='course_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_course', to='mainpage.course'),
        ),
    ]
