# Generated by Django 4.2.3 on 2023-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_coursereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='objective',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=9, max_digits=3, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.DeleteModel(
            name='CourseReview',
        ),
    ]
