# Generated by Django 4.2.2 on 2023-07-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='course_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_course', to='mainpage.course'),
        ),
    ]
