# Generated by Django 4.2.2 on 2023-07-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_course_description'),
        ('mainpage', '0004_alter_customgroup_course_owner'),
    ]

    operations = [
    ]
