# Generated by Django 4.2.2 on 2023-06-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons_count',
            field=models.IntegerField(default=0),
        ),
    ]
