# Generated by Django 4.2.3 on 2023-08-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_course_img'),
        ('mainpage', '0003_lessonregistration'),
        ('mainpage', '0004_rename_objective_review_course_and_more'),
    ]

    operations = [
    ]
