# Generated by Django 4.2.2 on 2023-06-20 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_alter_lesson_course_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_course', to='mainpage.course'),
        ),
    ]
