# Generated by Django 4.2.2 on 2023-06-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_course_lessons_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, default='Lesson 1', max_length=255),
        ),
    ]
