# Generated by Django 4.2.2 on 2023-07-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_lesson_start_time'),
        ('mainpage', '0006_chatmessage'),
    ]

    operations = [
    ]
