# Generated by Django 4.2.2 on 2023-06-14 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
