# Generated by Django 4.2.2 on 2023-06-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_alter_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], default='monday', max_length=10),
        ),
    ]
