# Generated by Django 4.2.2 on 2023-06-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_customgroup_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='title',
        ),
    ]
