# Generated by Django 4.2.2 on 2023-06-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_lesson_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessons_count',
            field=models.IntegerField(default=1),
        ),
    ]
