# Generated by Django 4.2.2 on 2023-06-20 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0010_alter_course_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='users',
            field=models.ManyToManyField(related_name='custom_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
