# Generated by Django 4.2.2 on 2023-06-16 07:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_customuser_phone_number_alter_course_mentor_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=375, max_length=128, region=None, unique=True),
        ),
    ]
