# Generated by Django 4.2.2 on 2023-06-21 16:34

import django.core.validators
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_customgroup_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('C++', 'C++'), ('Java', 'Java'), ('C#', 'C#'), ('Pascal', 'Pascal'), ('Frontend', 'Frontend')], default='Python', max_length=34, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Применяемы языки'),
        ),
    ]
