# Generated by Django 4.2.2 on 2023-06-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_alter_course_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='material',
            field=models.TextField(default='Полное описание', verbose_name='Полное описание'),
        ),
    ]
