# Generated by Django 4.2.2 on 2023-06-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_course_short_des'),
        ('mainpage', '0013_lesson_material'),
    ]

    operations = [
    ]
