# Generated by Django 4.2.2 on 2023-06-16 07:43

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'понедельник'), ('tuesday', 'вторник'), ('wednesday', 'среда'), ('thursday', 'четверг'), ('friday', 'пятница'), ('saturday', 'суббота'), ('sunday', 'воскресенье')], default='monday', max_length=56, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Начинающий'), ('Advanced', 'Продвинутый')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'понедельник'), ('tuesday', 'вторник'), ('wednesday', 'среда'), ('thursday', 'четверг'), ('friday', 'пятница'), ('saturday', 'суббота'), ('sunday', 'воскресенье')], default='monday', max_length=10),
        ),
    ]
