# Generated by Django 4.2.2 on 2023-06-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_alter_course_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='mentor_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_mentor', to='mainpage.customuser'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_course', to='mainpage.course'),
        ),
    ]
