# Generated by Django 4.2.2 on 2023-06-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_lesson_start_date_lesson_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time',
        ),
    ]
