# Generated by Django 4.2.2 on 2023-06-16 19:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0019_remove_lesson_start_date_remove_lesson_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='price',
            new_name='wallet',
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
    ]
