# Generated by Django 4.2.2 on 2023-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_lesson_course_owner'),
        ('registration', '0003_alter_customuser_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, to='mainpage.course'),
        ),
    ]
