# Generated by Django 4.2.2 on 2023-06-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_alter_course_technologies'),
        ('registration', '0005_alter_customuser_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', to='mainpage.customgroup'),
        ),
    ]
