version: '3'

services:
  web:
    build: .
    command: uvicorn it_school.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/it_school
    ports:
      - '8000:8000'
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  celery-worker:
    build: .
    command: celery -A celery_config worker --loglevel=info
    volumes:
      - .:/it_school
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A celery_config beat --loglevel=info
    volumes:
      - .:/it_school
    depends_on:
      - redis
